---
- hosts: apache
  sudo: yes
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

- name: apache2 listen to port 80
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" state=present
      notify:
        - restart apache2
-
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
